modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Wehavecookies56/EFMGender/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

authors="Wehavecookies56 aka Estelle"
description='''
Compatibility mod for Epic Fight with Wildfire's Female Gender Mod
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="epicfight"
    type="required"
    versionRange="[21.13,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="wildfire_gender"
    type="required"
    versionRange="[3.2,)"
    ordering="AFTER"
    side="BOTH"